name: Build Paddle OCR

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
   build_image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          
      - name: Install buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: divyam234
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image
        uses: docker/build-push-action@v3
        with:
          context: ./
          push: true
          tags: ghcr.io/${{ github.repository }}:latest